sonar.projectKey=agri-platform
sonar.projectName=SenAgriLink - Plateforme Agricole
sonar.projectVersion=1.0
sonar.sources=app
sonar.tests=tests
sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**,public/**,resources/**,database/**
sonar.sourceEncoding=UTF-8
